Feat: hecha la tarea A2.8-A
gii-is-psg2/psg2-2122-g4-43 pull request #32
Opened 2022-03-09 15:11 UTC by artrodase

2022-03-09 21:28 UTC, andrsdt requested changes
He dejado 6 comentarios a lo largo de varias líneas. Vendría bien arreglarlos para mejorar la calidad del código en cuanto a legibilidad

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelService.java
> +	public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
Esto tendría que estar en una clase Converter, no en el propio Service.
En el caso de mantenerlo en el service, el modificador de acceso debería ser `private`.

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelRepository.java
> +public interface PetHotelRepository extends Repository<PetHotel, Integer> {
Se puede extender `CrudRepository<PetHotel, Integer>` y no sería necesario declarar manualmente el método `save` despues

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelController.java
> +					"You have booked a room for %s from %s untill %s. You will recieve an email for confirmation!", pet,
"untill" debería ser "until". Falta de ortografía menor, no es prioritario cambiarlo

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotel.java
> +public class PetHotel extends BaseEntity{
Falta un espacio después de BaseEntity y antes de la llave para seguir las convenciones de código java.

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotel.java
> +@Entity
Podemos usar las anotaciones de Lombok `@Getter` y `@Setter` para prescindir de los mismos despues

2022-03-09 21:28 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/owner/OwnerRepository.java
> +	public Owner findOwnerUserName(@Param("userName") String userName);
No es necesario. Es más eficiente y simple hacer `owner.getUser().getUsername()` en el código, ya que la navegación de nuestro modelo nos lo permite. Esto sería necesario si no tuviéramos dichos atributos

2022-03-09 22:12 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelService.java
> +	public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
He creado una clase PetHotelDateToStringConverter

2022-03-09 22:14 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelRepository.java
> +public interface PetHotelRepository extends Repository<PetHotel, Integer> {
Buena observación. Hecho.

2022-03-09 22:15 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelController.java
> +					"You have booked a room for %s from %s untill %s. You will recieve an email for confirmation!", pet,
Es verdad. ¡Qué vergüenza!

2022-03-09 22:18 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotel.java
> +public class PetHotel extends BaseEntity{
Hecho.

2022-03-09 22:20 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotel.java
> +@Entity
Sí, no obstante, en el resto del proyecto no se utiliza Lombok, por lo que he decidido prescindir de él.

2022-03-09 22:25 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/owner/OwnerRepository.java
> +	public Owner findOwnerUserName(@Param("userName") String userName);
Aquí lo he hecho de esta manera, porque de todos los owners sólo necesito recuperar al owner que sea usuario autenticado en el sistema. Está implementado en initCreationForm y processCreationForm del PetHotelController. No lo veo hacer de la forma que tú dices en este caso. Lo dejo así, de momento.

2022-03-09 23:33 UTC, andrsdt approved these changes
A falta de un code smell menor podemos mergear estos cambios. Se corregirá en los toques finales del release

2022-03-09 23:33 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/pethotel/PetHotelService.java
> +//	public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
Siguiendo las buenas prácticas no tendríamos que tener código comentado, está en git para cuando queramos recuperarlo. Lo eliminaré cuando prepare el proyecto para la release

2022-03-09 23:33 UTC, merged

2022-03-10 17:11 UTC, andrsdt commented
Ahora todo está mejor. Hay pequeños cambios menores pendientes, sobre todo de formato, que se corregirán antes de la release