Feat: hecha la tarea A2.8-C
gii-is-psg2/psg2-2122-g4-43 pull request #36
Opened 2022-03-09 21:04 UTC by jonatep

2022-03-09 22:51 UTC, artrodase requested changes
He clonado tu rama y va todo según lo esperado. No obstante, falta resolver conflictos con la rama develop para poder hacer merge + una pequeña observación abajo.

2022-03-09 22:51 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/vet/SpecialtyFormatter.java
> +public class SpecialtyFormatter implements Formatter<Specialty>{
Falta un espacio entre Formatter<Specialty> y la llave para seguir las convenciones de código java.

2022-03-10 17:17 UTC, jonatep commented
Resueltos los conflictos y aplicado el estándar de código

2022-03-10 17:19 UTC, jonatep commented on src/main/java/org/springframework/samples/petclinic/vet/SpecialtyFormatter.java
> +public class SpecialtyFormatter implements Formatter<Specialty>{
Ya cambiado :)

2022-03-10 18:13 UTC, artrodase requested changes

2022-03-10 18:13 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/vet/VetRepository.java
> +	Vet findById(int id);
Existe otro método con el mismo nombre en la línea 46. Deberías eliminarlo o renombrarlo.

2022-03-10 18:20 UTC, jonatep commented on src/main/java/org/springframework/samples/petclinic/vet/VetRepository.java
> +	Vet findById(int id);
Ya lo eliminé :)

2022-03-10 18:29 UTC, artrodase commented
Todo bien. Hago merge.

2022-03-10 18:29 UTC, merged