Merge branch 'release/V2.0.0' into main
gii-is-psg2/psg2-2122-g4-43 pull request #77
Opened 2022-04-13 22:16 UTC by andrsdt

Código revisado para llevar a cabo la release del sprint 3. Trae pequeños cambios en el formato y en el estilo del código para adaptarlo a los estándares, así como toda la funcionalidad nueva implementada en el sprint.

Ref #76 (La pull request origianl se ha cerrado automáticamente tras cambiar el nombre a la rama de `release/V1.1.0` a `release/V2.0.0` y ha sido necesaria crear una nueva)

2022-04-14 00:51 UTC, artrodase requested changes
Hay algunas cosas a corregir antes de hacer merge con la rama máster:
1) Atendiendo las recomendaciones del Product Owner sobre el formulario de "causas" creo que deberíamos mejorar el formulario del Pet Hotel de la misma manera. Concretamente, no permitir que se envíe el formulario sin rellenar todos los campos, ya que son obligatorios (para evitar la redirección a la página de error) con el correspondiente mensaje de error.
2) Aún quedan algunos warnings

2022-04-14 00:51 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
>  				.antMatchers("/pethotels/**").hasAnyAuthority("owner").antMatchers("/users/new")
la línea 12 de este fichero: eliminar import no utilizado

2022-04-14 08:49 UTC, andrsdt commented on src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
>  				.antMatchers("/pethotels/**").hasAnyAuthority("owner").antMatchers("/users/new")
Se trata de un warning de que usar `NoOpPasswordEncoder` no es seguro y que está en desuso, ya que sirve para almacenar las contraseñas en texto plano. Como no es una aplicación para producción, lo dejaremos así e ignoraremos el aviso (la solución sería almacenar las contraseñas encriptadas usando BCrypt)

2022-04-14 18:35 UTC, artrodase requested changes
Estimado compañero, aún deberíamos mejorar las validaciones.

2022-04-14 18:35 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
> +		if (result.hasErrors() || cause.getName().isEmpty() || cause.getDescription().isEmpty()
En este caso tal cual está hecho hace que no se visualiza la validación personalizada del campo "Objetivo Recaudación", ya que el mensaje de error de este campo se envía a través de model.put. En nuestro caso al haber "redirect", deberíamos utilizar redirectAttributes.addFlashAttribute, por ejemplo. O hacer otro if en su caso.

2022-04-14 18:35 UTC, artrodase commented on src/main/java/org/springframework/samples/petclinic/cause/CauseController.java
> +				model.put("org.springframework.validation.BindingResult.donation", result);
Debería ser org.springframework.validation.BindingResult.**cause**

2022-04-15 12:44 UTC, artrodase approved these changes
Una vez revisado todos los cambios, confirmo que el trabajo es correcto,

2022-04-15 12:45 UTC, merged